export const alternateSpellings: { [key: string]: string } = {
  drc: "Democratic Republic of the Congo",
  usa: "United States",
  uae: "United Arab Emirates",
  uk: "United Kingdom",
  america: "United States",
  unitedstatesofamerica: "United States",
  car: "Central African Republic",
  vatican: "Vatican City",
  stkittsandnevis: "Saint Kitts and Nevis",
  stkitts: "Saint Kitts and Nevis",
  stlucia: "Saint Lucia",
  stvincentandthegrenadines: "Saint Vincent and the Grenadines",
  stvincent: "Saint Vincent and the Grenadines",
  czechia: "Czech Republic",
  macedonia: "North Macedonia",
  bosnia: "Bosnia and Herzegovina",
  holysee: "Vatican City",
  thenetherlands: "Netherlands",
  thebahamas: "Bahamas",
  kiev: "Kyiv",
  theukraine: "Ukraine",
  stjohns: "Saint John's",
  stgeorges: "Saint George's",
  saotome: "Sao Tome",
  srijayawardenepurakotte: "Colombo",
  srijayawardenepura: "Colombo",
  capetown: "Pretoria",
  bloemfontein: "Pretoria",
  trinidad: "Trinidad and Tobago",
};
